name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set timezone to America/Sao_Paulo
        run: sudo timedatectl set-timezone America/Sao_Paulo

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Run Tests
        run: make test

      - name: Build Application
        run: make release VERSION=${GITHUB_REF#refs/tags/}

      - name: Package Binary
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          ARCHIVE_NAME="go-imapsync_${VERSION}_linux_amd64.tar.gz"
          tar -czvf "$ARCHIVE_NAME" -C dist go-imapsync -C .. LICENSE README.md examples/
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
